datasets:
  # - bdd
  # - lvis
  # - coco
  - objectnet
shared_session_params: # see SessionParams
  batch_size: 1
  shortlist_size: 50
shared_bench_params: # see BenchParams
  max_feedback: null
  box_drop_prob: 0. 
  max_results: 10 # max positive results
  n_batches : 30 # max batches
  provide_textual_feedback: False
  query_template : "a {}"
variants:
    - name: seesaw_all
      interactive: pytorch
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    # - name: seesaw_multi
    #   interactive: plain
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    - name: seesaw_knn5
      knn_k : 5
      interactive: knn_greedy
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: seesaw_knn3
      knn_k : 3
      interactive: knn_greedy
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: seesaw_knn10
      knn_k : 10
      interactive: knn_greedy
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: seesaw_knn20
      knn_k : 20
      interactive: knn_greedy
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: baseline
      interactive: plain
      index_name: coarse