datasets:
  # - bdd
  - lvis
  # - coco
  - objectnet
shared_session_params: # see SessionParams
  batch_size: 1
  shortlist_size: 50
shared_bench_params: # see BenchParams
  max_feedback: null
  box_drop_prob: 0. 
  max_results: 10 # max positive results
  n_batches : 30 # max batches
  provide_textual_feedback: False
  query_template : "a {}"
variants:
    # - name: seesaw_knn5
    #   knn_k : 5
    #   interactive: knn_greedy
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_label_prop
    #   knn_k : 5
    #   interactive: knn_prop
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_linear_prop
    #   interactive: linear_prop
    #   knn_k: 5
    #   interactive_options:
    #     linear_kwargs:
    #       C: 10
    #       solver_flags:
    #         solver: 'MOSEK'
    #         verbose: False
    #     pca_kwargs:
    #       n_components: 128
    #       whiten: True
    #     label_prop_kwargs:
    #       calib_a: 10.
    #       calib_b: -5
    #       prior_weight: 1.
    #       edist: .1
    #       num_iters: 5
    #     sample_size: 4000
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    - name: seesaw_knn_prop
      interactive: knn_prop
      knn_k: 5
      interactive_options:
          calib_a: 10.
          calib_b: -5
          prior_weight: 1.
          edist: .1
          num_iters: 5
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater