datasets:
  # - bdd
  - name: lvis
    # categories: 
    #    - ladder
  # - name: objectnet
shared_session_params: # see SessionParams
  batch_size: 1
  shortlist_size: 50
  index_options : 
    use_vec_index : False
shared_bench_params: # see BenchParams
  max_feedback: null
  box_drop_prob: 0. 
  max_results: 10 # max positive results
  n_batches : 30 # max batches
  provide_textual_feedback: False
  query_template : "a {}"
variants:
    # - name: seesaw_knn5
    #   interactive: knn_greedy
    #   interactive_options:
    #     knn_k: 5
    #     knn_path: dividx
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn10
    #   interactive: knn_greedy
    #   interactive_options:
    #     knn_k: 10
    #     knn_path: dividx
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn_prop5
    #   interactive: knn_prop
    #   interactive_options:
    #     knn_k: 5
    #     knn_path: dividx
    #     calib_a: 10.
    #     calib_b: -5
    #     prior_weight: 1.
    #     edist: .2
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn_prop_nodiv_iters5
    #   interactive: knn_prop2
    #   interactive_options:
    #     knn_k: 6
    #     # knn_path: dividx
    #     calib_a: 10.
    #     calib_b: -5
    #     prior_weight: 1.
    #     edist: .1
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    - name: knn_prop2
      max_trials: 30
      interactive: knn_prop2
      interactive_options:
        knn_k: 
          choose : [20]
        num_iters: 
          choose : [29]
        # knn_path: dividx
        calib_a: 
          choose : [15]
        calib_b: 
          choose : [-0.5]
        prior_weight: 
          choose: [3.]
        edist: 
          choose : [.1]
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    # - name: seesaw_knn_prop_simplediv
    #   interactive: knn_prop2
    #   interactive_options:
    #     knn_k: 10
    #     knn_path: dividx
    #     intra_knn_k: 0
    #     calib_a: 10.
    #     calib_b: -5
    #     prior_weight: 1.
    #     edist: .1
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn_prop_compositediv
    #   interactive: knn_prop2
    #   interactive_options:
    #     knn_k: 5
    #     knn_path: dividx
    #     intra_knn_k: 2
    #     calib_a: 10.
    #     calib_b: -5
    #     prior_weight: 1.
    #     edist: .1
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # # test refactored old
    # - name: seesaw_knn_prop_older
    #   interactive: knn_prop
    #   interactive_options:
    #     knn_k: 10
    #     knn_path: dividx
    #     calib_a: 10.
    #     calib_b: -5
    #     prior_weight: 1.
    #     edist: .1
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn_prop_older_nodiv_rescaled
    #   interactive: knn_prop
    #   interactive_options:
    #     knn_k: 10
    #     calib_a: 1.
    #     calib_b: -1.
    #     prior_weight: 1.
    #     edist: .1
    #     num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater
    # - name: seesaw_knn_prop20
    #   interactive: knn_prop
    #   interactive_options:
    #       knn_k: 20
    #       knn_path: exact
    #       calib_a: 10.
    #       calib_b: -5
    #       prior_weight: 1.
    #       edist: .1
    #       num_iters: 5
    #   index_name: multiscale
    #   agg_method: avg_score
    #   aug_larger: greater