datasets:
  - bdd
  - lvis
  - coco
  - objectnet
shared_session_params: # see SessionParams
  batch_size: 1
  shortlist_size: 50
shared_bench_params: # see BenchParams
  max_feedback: null
  box_drop_prob: 0. 
  max_results: 10 # max positive results
  n_batches : 30 # max batches
  provide_textual_feedback: False
  query_template : "a {}"
variants:
    - name: seesaw_log_reg2_1
      interactive: log_reg2
      interactive_options:
        class_weights: balanced
        scale: centered
        reg_lambda: 1
        max_iter: 200.
        lr: 1
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: seesaw_log_reg2_3
      interactive: log_reg2
      interactive_options:
        class_weights: balanced
        scale: centered
        reg_lambda: 3.3
        max_iter: 200.
        lr: 1
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: seesaw_log_reg2_10
      interactive: log_reg2
      interactive_options:
        class_weights: balanced
        scale: centered
        reg_lambda: 10
        max_iter: 200.
        lr: 1
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater