datasets:
  # - bdd
  - name: lvis
    # categories: 
    #   - zebra
    # - coco
  - objectnet
shared_session_params: # see SessionParams
  batch_size: 1
  shortlist_size: 50
  index_options: 
    use_vec_index: False
shared_bench_params: # see BenchParams
  max_feedback: null
  box_drop_prob: 0. 
  max_results: 10 # max positive results
  n_batches : 30 # max batches
  provide_textual_feedback: False
  query_template : "a {}"
variants:
    - name: pseudo_lr_switch_ng
      max_samples : 10
      interactive: pseudo_lr
      interactive_options:
        switch_over: True
        log_reg_params:
          class_weights: 1.
          scale: centered
          reg_lambda: 10. # enough pseudolabels
          max_iter: 200.
          lr: 1
        label_prop_params:
          knn_k: 20
          knn_path: ''
          calib_a: 
            choose: [1.] #[.2, .5, 1., 2.]
          calib_b: 
            choose: [-2.] #, -1., -.5, 0., .5]
          prior_weight: 1.
          edist: .1
          num_iters: 5
        sample_size: 5000
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater
    - name: pseudo_lr_ng
      interactive: pseudo_lr
      interactive_options:
        switch_over: False
        log_reg_params:
          class_weights: 1.
          scale: centered
          reg_lambda: 10. # enough pseudolabels
          max_iter: 200.
          lr: 1
        label_prop_params:
          knn_k: 20
          knn_path: ''
          calib_a: 
            choose: [1.] #[.2, .5, 1., 2.]
          calib_b: 
            choose: [-2.] #, -1., -.5, 0., .5]
          prior_weight: 1.
          edist: .1
          num_iters: 5
        sample_size: 5000
      index_name: multiscale
      agg_method: avg_score
      aug_larger: greater

