shared_session_params:
  batch_size: 1
  shortlist_size: 50
  index_options: 
    use_vec_index: False
  index_name: multiscale
  agg_method: plain_score
  aug_larger: greater
- name: pseudo_lr_switch
  max_samples: 10
  interactive: pseudo_lr
  interactive_options:
    switch_over: True
    real_sample_weight: 
      choose: [1.]
    sample_size: 
      choose : [10000]
    log_reg_params:
      class_weights: 
        choose: [1.]
      scale: centered
      reg_lambda: 
        choose: [.3] 
      max_iter: 200.
      lr: 1
      fit_intercept: false
    label_prop_params:
      self_edges : True
      normalized_weights : False
      normalize_scores : False
      sigmoid_before_propagate: True
      knn_k: 
        choose: [20]
      knn_path: nndescent60
      calib_a: 
        choose: [10.]
      calib_b: 
        choose: [-0.4]
      prior_weight: 
        choose: [1.] # good for unnormalized
      edist: 
        choose: [.05]